program test 
defines {
	function test uses (integers val) returns integers catchable
	defines {
		print val
		return val
	}
	
	do {
		let x be integers assign [3,4,5,6]
		print call test with (x)
	} catch {
		print "fail"
	}
}
